auto_scale_lr = dict(base_batch_size=32, enable=False)
backend_args = None
checkpoint_config = dict(interval=1)
class_names = [
    'Car',
    'Pedestrian',
    'Cyclist',
]
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'configs.cbam_ensemble_vlm.cbam_ensemble_vlm_film',
    ])
data_root = '/data/ataparia/LidarTraining/night-day-frames/'
dataset_type = 'WaymoDataset'
db_sampler = dict(
    backend_args=None,
    classes=[
        'Car',
        'Pedestrian',
        'Cyclist',
    ],
    data_root='/data/ataparia/LidarTraining/night-day-frames/',
    info_path=
    '/data/ataparia/LidarTraining/night-day-frames/waymo_dbinfos_train.pkl',
    points_loader=dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=6,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    prepare=dict(
        filter_by_difficulty=[
            -1,
        ],
        filter_by_min_points=dict(Car=5, Cyclist=5, Pedestrian=5)),
    rate=1.0,
    sample_groups=dict(Car=15, Cyclist=10, Pedestrian=10))
dist_params = dict(backend='nccl')
input_modality = dict(use_camera=True, use_lidar=True)
launcher = 'none'
load_from = None
log_config = dict(
    hooks=[
        [
            dict(type='LocalVisBackend'),
            dict(type='TensorboardVisBackend'),
            dict(
                init_kwargs=dict(
                    mode='online',
                    name='cbam_ensemble_vlm_film',
                    project='MMdet_LiDAR_ObjectDetection'),
                type='WandbVisBackend'),
        ],
        dict(
            name='visualizer',
            type='DetLocalVisualizer',
            vis_backends=[
                dict(type='LocalVisBackend'),
                dict(type='TensorboardVisBackend'),
                dict(
                    init_kwargs=dict(
                        mode='online',
                        name='cbam_ensemble_vlm_film',
                        project='MMdet_LiDAR_ObjectDetection'),
                    type='WandbVisBackend'),
            ]),
    ],
    interval=50)
log_level = 'INFO'
lr_config = dict(
    policy='step',
    step=[
        20,
        23,
    ],
    warmup='linear',
    warmup_iters=1000,
    warmup_ratio=0.001)
metainfo = dict(classes=[
    'Car',
    'Pedestrian',
    'Cyclist',
])
model = dict(
    backbone=dict(
        in_channels=384,
        layer_nums=[
            5,
            5,
        ],
        layer_strides=[
            1,
            2,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='naiveSyncBN2d'),
        out_channels=[
            128,
            256,
        ],
        type='SECOND'),
    bbox_head=dict(
        anchor_generator=dict(
            ranges=[
                [
                    -76.8,
                    -51.2,
                    -0.0345,
                    76.8,
                    51.2,
                    -0.0345,
                ],
                [
                    -76.8,
                    -51.2,
                    0,
                    76.8,
                    51.2,
                    0,
                ],
                [
                    -76.8,
                    -51.2,
                    -0.1188,
                    76.8,
                    51.2,
                    -0.1188,
                ],
            ],
            reshape_out=False,
            rotations=[
                0,
                1.57,
            ],
            sizes=[
                [
                    4.73,
                    2.08,
                    1.77,
                ],
                [
                    0.91,
                    0.84,
                    1.74,
                ],
                [
                    1.81,
                    0.84,
                    1.77,
                ],
            ],
            type='AlignedAnchor3DRangeGenerator'),
        bbox_coder=dict(code_size=7, type='DeltaXYZWLHRBBoxCoder'),
        diff_rad_by_sin=True,
        dir_offset=-0.7854,
        feat_channels=512,
        in_channels=512,
        loss_bbox=dict(
            beta=0.1111111111111111,
            loss_weight=1.0,
            type='mmdet.SmoothL1Loss'),
        loss_cls=dict(
            alpha=0.25,
            gamma=2.0,
            loss_weight=1.0,
            type='mmdet.FocalLoss',
            use_sigmoid=True),
        loss_dir=dict(
            loss_weight=0.2, type='mmdet.CrossEntropyLoss', use_sigmoid=False),
        num_classes=3,
        type='Anchor3DHead',
        use_direction_classifier=True),
    lidar_model_cfg_path='configs/second_detr_ensemble.py',
    lidar_model_path=
    '/data/ataparia/mmdet_lidar/work_dirs/second/epoch_100.pth',
    neck=dict(
        in_channels=[
            128,
            256,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='naiveSyncBN2d'),
        out_channels=[
            256,
            256,
        ],
        type='SECONDFPN',
        upsample_strides=[
            1,
            2,
        ]),
    rgb_model_path=
    '/data/ataparia/RGBTraining/trained_models/rgb_fulldata/checkpoint-190000',
    test_cfg=dict(
        max_num=500,
        min_bbox_size=0,
        nms_across_levels=False,
        nms_pre=4096,
        nms_thr=0.25,
        score_thr=0.1,
        use_rotate_nms=True),
    test_jsonl_file='conditions/smolvlm_conditions/dawn_dusk_testing.jsonl',
    train_cfg=dict(
        allowed_border=0,
        assigner=[
            dict(
                ignore_iof_thr=-1,
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                min_pos_iou=0.4,
                neg_iou_thr=0.4,
                pos_iou_thr=0.55,
                type='mmdet.MaxIoUAssigner'),
            dict(
                ignore_iof_thr=-1,
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                min_pos_iou=0.3,
                neg_iou_thr=0.3,
                pos_iou_thr=0.5,
                type='mmdet.MaxIoUAssigner'),
            dict(
                ignore_iof_thr=-1,
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                min_pos_iou=0.3,
                neg_iou_thr=0.3,
                pos_iou_thr=0.5,
                type='mmdet.MaxIoUAssigner'),
        ],
        code_weight=[
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
        ],
        debug=False,
        pos_weight=-1),
    train_jsonl_file='conditions/night-day_training.jsonl',
    type='CBAMEnsembleVLMFiLM',
    val_jsonl_file='conditions/night-day_validation.jsonl')
momentum_config = None
mp_start_method = 'fork'
opencv_num_threads = 0
optim_wrapper = dict(
    optimizer=dict(lr=0.001, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
optimizer = dict(lr=0.001, type='AdamW', weight_decay=0.01)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
point_cloud_range = [
    -76.8,
    -51.2,
    -2,
    76.8,
    51.2,
    4,
]
resume = True
resume_from = None
runner = dict(max_epochs=24, type='EpochBasedRunner')
test_cfg = dict(type='TestLoop')
test_data_root = '/data/ataparia/LidarTraining/dawn_dusk-frames/'
test_dataloader = dict(
    batch_size=4,
    dataset=dict(
        ann_file='waymo_infos_test.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(img='testing/image_0', pts='testing/velodyne'),
        data_root='/data/ataparia/LidarTraining/dawn_dusk-frames/',
        metainfo=dict(classes=[
            'Car',
            'Pedestrian',
            'Cyclist',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=6,
                type='LoadPointsFromFile',
                use_dim=5),
            dict(
                backend_args=None,
                data_root=
                '/data/ataparia/LidarTraining/dawn_dusk-frames/testing/image_0',
                type='LoadImageFromFile'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(type='RandomFlip3D'),
                    dict(
                        point_cloud_range=[
                            -76.8,
                            -51.2,
                            -2,
                            76.8,
                            51.2,
                            4,
                        ],
                        type='PointsRangeFilter'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(
                keys=[
                    'points',
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_bboxes',
                    'gt_labels',
                ],
                meta_keys=[
                    'box_type_3d',
                    'sample_idx',
                    'context_name',
                    'timestamp',
                    'img_path',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='WaymoDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    type='WaymoMetric', waymo_bin_file='gt_dawn_dusk_testing.bin')
test_pipeline = [
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=6,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        data_root=
        '/data/ataparia/LidarTraining/dawn_dusk-frames/testing/image_0',
        type='LoadImageFromFile'),
    dict(
        flip=False,
        img_scale=(
            1333,
            800,
        ),
        pts_scale_ratio=1,
        transforms=[
            dict(
                rot_range=[
                    0,
                    0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0,
                    0,
                    0,
                ],
                type='GlobalRotScaleTrans'),
            dict(type='RandomFlip3D'),
            dict(
                point_cloud_range=[
                    -76.8,
                    -51.2,
                    -2,
                    76.8,
                    51.2,
                    4,
                ],
                type='PointsRangeFilter'),
        ],
        type='MultiScaleFlipAug3D'),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes',
            'gt_labels',
        ],
        meta_keys=[
            'box_type_3d',
            'sample_idx',
            'context_name',
            'timestamp',
            'img_path',
        ],
        type='Pack3DDetInputs'),
]
train_cfg = dict(max_epochs=50, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_size=4,
    dataset=dict(
        dataset=dict(
            ann_file='waymo_infos_train.pkl',
            backend_args=None,
            box_type_3d='LiDAR',
            data_prefix=dict(img='training/image_0', pts='training/velodyne'),
            data_root='/data/ataparia/LidarTraining/night-day-frames/',
            load_interval=5,
            modality=dict(use_camera=True, use_lidar=True),
            pipeline=[
                dict(
                    backend_args=None,
                    coord_type='LIDAR',
                    load_dim=6,
                    type='LoadPointsFromFile',
                    use_dim=5),
                dict(
                    backend_args=None,
                    data_root=
                    '/data/ataparia/LidarTraining/night-day-frames/training/image_0',
                    type='LoadImageFromFile'),
                dict(
                    type='LoadAnnotations3D',
                    with_bbox_3d=True,
                    with_label_3d=True),
                dict(
                    flip_ratio_bev_horizontal=0.5,
                    flip_ratio_bev_vertical=0.5,
                    sync_2d=False,
                    type='RandomFlip3D'),
                dict(
                    rot_range=[
                        -0.78539816,
                        0.78539816,
                    ],
                    scale_ratio_range=[
                        0.95,
                        1.05,
                    ],
                    type='GlobalRotScaleTrans'),
                dict(
                    point_cloud_range=[
                        -76.8,
                        -51.2,
                        -2,
                        76.8,
                        51.2,
                        4,
                    ],
                    type='PointsRangeFilter'),
                dict(
                    point_cloud_range=[
                        -76.8,
                        -51.2,
                        -2,
                        76.8,
                        51.2,
                        4,
                    ],
                    type='ObjectRangeFilter'),
                dict(type='PointShuffle'),
                dict(
                    keys=[
                        'points',
                        'img',
                        'gt_bboxes_3d',
                        'gt_labels_3d',
                        'gt_bboxes',
                        'gt_labels',
                    ],
                    meta_keys=[
                        'box_type_3d',
                        'sample_idx',
                        'context_name',
                        'timestamp',
                        'img_path',
                    ],
                    type='Pack3DDetInputs'),
            ],
            test_mode=False,
            type='WaymoDataset'),
        times=2,
        type='RepeatDataset'),
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=6,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        data_root=
        '/data/ataparia/LidarTraining/night-day-frames/training/image_0',
        type='LoadImageFromFile'),
    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True),
    dict(
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5,
        sync_2d=False,
        type='RandomFlip3D'),
    dict(
        rot_range=[
            -0.78539816,
            0.78539816,
        ],
        scale_ratio_range=[
            0.95,
            1.05,
        ],
        type='GlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            -76.8,
            -51.2,
            -2,
            76.8,
            51.2,
            4,
        ],
        type='PointsRangeFilter'),
    dict(
        point_cloud_range=[
            -76.8,
            -51.2,
            -2,
            76.8,
            51.2,
            4,
        ],
        type='ObjectRangeFilter'),
    dict(type='PointShuffle'),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes',
            'gt_labels',
        ],
        meta_keys=[
            'box_type_3d',
            'sample_idx',
            'context_name',
            'timestamp',
            'img_path',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=4,
    dataset=dict(
        ann_file='waymo_infos_val.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(img='training/image_0', pts='training/velodyne'),
        data_root='/data/ataparia/LidarTraining/night-day-frames/',
        metainfo=dict(classes=[
            'Car',
            'Pedestrian',
            'Cyclist',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=6,
                type='LoadPointsFromFile',
                use_dim=5),
            dict(
                backend_args=None,
                data_root=
                '/data/ataparia/LidarTraining/night-day-frames/training/image_0',
                type='LoadImageFromFile'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(type='RandomFlip3D'),
                    dict(
                        point_cloud_range=[
                            -76.8,
                            -51.2,
                            -2,
                            76.8,
                            51.2,
                            4,
                        ],
                        type='PointsRangeFilter'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(
                keys=[
                    'points',
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_bboxes',
                    'gt_labels',
                ],
                meta_keys=[
                    'box_type_3d',
                    'sample_idx',
                    'context_name',
                    'timestamp',
                    'img_path',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='WaymoDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(type='WaymoMetric', waymo_bin_file='gt_validation.bin')
val_pipeline = [
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=6,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        data_root=
        '/data/ataparia/LidarTraining/night-day-frames/training/image_0',
        type='LoadImageFromFile'),
    dict(
        flip=False,
        img_scale=(
            1333,
            800,
        ),
        pts_scale_ratio=1,
        transforms=[
            dict(
                rot_range=[
                    0,
                    0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0,
                    0,
                    0,
                ],
                type='GlobalRotScaleTrans'),
            dict(type='RandomFlip3D'),
            dict(
                point_cloud_range=[
                    -76.8,
                    -51.2,
                    -2,
                    76.8,
                    51.2,
                    4,
                ],
                type='PointsRangeFilter'),
        ],
        type='MultiScaleFlipAug3D'),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes',
            'gt_labels',
        ],
        meta_keys=[
            'box_type_3d',
            'sample_idx',
            'context_name',
            'timestamp',
            'img_path',
        ],
        type='Pack3DDetInputs'),
]
work_dir = 'YOUR_PATH/cbam_ensemble_vlm_film_30_conditions'
workflow = [
    (
        'train',
        1,
    ),
]
